### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by allrude** [timoffmax/magento2_topbar#1] opened 2019-01-29 17:24 UTC
Hi I installed the module on a clean M2.3 install but it doesn't work, i see it on the backend but not the frontend

**Comment by timoffmax** [comment] 2019-01-31 14:37
> Hi I installed the module on a clean M2.3 install but it doesn't work, i see it on the backend but not the frontend

Hi @allrude ! Sorry, but I can't reproduce your problem. I've used clean Magento 2.3.0 CE installation (it had been downloaded from official Magento site) and PHP 7.2.14.
Did you enable the module in **Stores -> Settings -> Configuration -> Timoffmax -> Top Information Bar**?
I've added some clarification in README.md, please take a look.

Let me know if you still have questions.

**Comment by timoffmax** [comment] 2019-03-07 05:36
I close it because I can't reproduce the problem and don't get any response for a long time.

**Closed as completed by timoffmax** 2019-03-07 05:36 UTC
